---
- hosts: all
  remote_user: test1
  become: true
  become_method: su
  become_user: root
  tasks:
    - name: install sudo package
      apt:
        name: sudo
        state: present

    - name: add user to sudoers
      user:
        name: test1
        append: yes
        groups: sudo

    - name: deploy ssh pub key to remote
      authorized_key:
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDl6/wHTnf+Q0rW+SKdplqtlRb18SbuEhMQ+5Da4wnEe9SB4t36VyMlQmEBSVtguPbBqUd0IheytCtwNnFRWpto8ct6dXhv1F7F//wfdDS4JHK6VUty9SYlyDi64iWLX9QgrrBcOX4+bek5RZdcWbds+ll99UXm5RFoJtkPrAQrYltM/zyrCy0993iz2Wei9VdKnOstA3xTluPf6L5WiYkOKt8uTROymcvmcCVTjacLhRar9fFv4j5vo1lnZvS+A65c0nXhFeL7dot263fzNMdHYGhKwMO71x1d+y2PENMbekXkKD7N59lr437sbRZwA1HtP+IPauWT9+WnhiUOR+G9 ylagtab@e1r7p15.1337.ma
        user: test1

    - name: remove root password
      shell: passwd -d root
